apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-secret-store
  namespace: tecpet-dev-app
spec:
  provider:
    gcpsm:
      projectID: "techpet-dev-01"
      # The auth section configures how ESO authenticates to GCP.
      # By default, it will use the GKE node's service account (Workload Identity).
      auth:
        workloadIdentity:
          clusterLocation: "us-central1"
          clusterName: "dev-gke-autopilot-cluster"
          serviceAccountRef:
            name: "tecpet-app-gke-sa" # The KSA linked to the GCP SA
            namespace: "tecpet-dev-app"
