apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: botflow-builder-backendconfig
  namespace: tecpet-dev-app
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 3000
    type: HTTP
    requestPath: /
