// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from "@typebot.io/forge";
import { tecpetBlock } from ".";
import { auth } from "./auth";

export const tecpetBlockSchema = parseBlockSchema(tecpetBlock);
export const tecpetCredentialsSchema = parseBlockCredentials(
  tecpetBlock.id,
  auth.schema,
);
