export enum ChatbotActionButtonTypeEnum {
  NONE = "NONE",
  BACK_TO_HOME = "BACK_TO_HOME",
  BOOKING_CONFIRM = "BOOKING_CONFIRM",
  BOOKING_CANCEL = "BOOKING_CANCEL",
  BOOKING_RESCHEDULE = "BOOKING_RESCHEDULE",
  BOOKING_CREATE = "BOOKING_CREATE",
  REMEMBER_ME_LATER = "REMEMBER_ME_LATER",
  TRANSFER_TO_HUMAN = "TRANSFER_TO_HUMAN",
  PAY_INVOICE_WITH_VOUCHER = "PAY_INVOICE_WITH_VOUCHER",
  CALL = "CALL",
  URL = "URL",
  END = "END",
}
